export const surahsList = [
 {
    surahNo: 1,
    title: 'Al-Fatiha',
    arabicTitle: 'الفاتحة',
    englishTitle: 'The Opening',
    // url: require('../../src/assets/audio/a_rehman_sudais/1.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 2,
    title: 'Al-Baqarah',
    arabicTitle: 'البقرة',
    englishTitle: 'The Cow',
    // url: require('../../src/assets/audio/a_rehman_sudais/2.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 3,
    title: 'Al-Imran',
    arabicTitle: 'آل عمران',
    englishTitle: 'The Family of Imran',
    // url: require('../../src/assets/audio/a_rehman_sudais/3.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 4,
    title: 'An-Nisa',
    arabicTitle: 'النساء',
    englishTitle: 'The Women',
    // url: require('../../src/assets/audio/a_rehman_sudais/4.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 5,
    title: 'Al-Maidah',
    arabicTitle: 'المائدة',
    englishTitle: 'The Table Spread',
    // url: require('../../src/assets/audio/a_rehman_sudais/5.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 6,
    title: 'Al-Anam',
    arabicTitle: 'الأنعام',
    englishTitle: 'The Cattle',
    // url: require('../../src/assets/audio/a_rehman_sudais/6.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 7,
    title: 'Al-Araf',
    arabicTitle: 'الأعراف',
    englishTitle: 'The Heights',
    // url: require('../../src/assets/audio/a_rehman_sudais/7.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 8,
    title: 'Al-Anfal',
    arabicTitle: 'الأنفال',
    englishTitle: 'The Spoils of War',
    // url: require('../../src/assets/audio/a_rehman_sudais/8.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 9,
    title: 'At-Tawbah',
    arabicTitle: 'التوبة',
    englishTitle: 'The Repentance',
    // url: require('../../src/assets/audio/a_rehman_sudais/9.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 10,
    title: 'Yunus',
    arabicTitle: 'يونس',
    englishTitle: 'Jonah',
    // url: require('../../src/assets/audio/a_rehman_sudais/10.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 11,
    title: 'Hud',
    arabicTitle: 'هود',
    englishTitle: 'Prophet Hud',
    // url: require('../../src/assets/audio/a_rehman_sudais/11.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 12,
    title: 'Yusuf',
    arabicTitle: 'يوسف',
    englishTitle: 'Joseph',
    // url: require('../../src/assets/audio/a_rehman_sudais/12.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 13,
    title: 'Ar-Rad',
    arabicTitle: 'الرعد',
    englishTitle: 'The Thunder',
    // url: require('../../src/assets/audio/a_rehman_sudais/13.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 14,
    title: 'Ibrahim',
    arabicTitle: 'ابراهيم',
    englishTitle: 'Abraham',
    // url: require('../../src/assets/audio/a_rehman_sudais/14.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 15,
    title: 'Al-Hijr',
    arabicTitle: 'الحجر',
    englishTitle: 'The Rocky Tract',
    // url: require('../../src/assets/audio/a_rehman_sudais/15.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 16,
    title: 'An-Nahl',
    arabicTitle: 'النحل',
    englishTitle: 'The Bee',
    // url: require('../../src/assets/audio/a_rehman_sudais/16.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 17,
    title: 'Al-Isra',
    arabicTitle: 'الإسراء',
    englishTitle: 'The Night Journey',
    // url: require('../../src/assets/audio/a_rehman_sudais/17.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 18,
    title: 'Al-Kahf',
    arabicTitle: 'الكهف',
    englishTitle: 'The Cave',
    // url: require('../../src/assets/audio/a_rehman_sudais/18.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 19,
    title: 'Maryam',
    arabicTitle: 'مريم',
    englishTitle: 'Maryam',
    // url: require('../../src/assets/audio/a_rehman_sudais/19.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 20,
    title: 'Ta-Ha',
    arabicTitle: 'طه',
    englishTitle: 'Ta-Ha',
    // url: require('../../src/assets/audio/a_rehman_sudais/20.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 21,
    title: 'Al-Anbiya',
    arabicTitle: 'الأنبياء',
    englishTitle: 'The Prophets',
    // url: require('../../src/assets/audio/a_rehman_sudais/21.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 22,
    title: 'Al-Hajj',
    arabicTitle: 'الحج',
    englishTitle: 'The Pilgrimage',
    // url: require('../../src/assets/audio/a_rehman_sudais/22.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 23,
    title: 'Al-Muminun',
    arabicTitle: 'المؤمنون',
    englishTitle: 'The Believers',
    // url: require('../../src/assets/audio/a_rehman_sudais/23.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 24,
    title: 'An-Nur',
    arabicTitle: 'النور',
    englishTitle: 'The Light',
    // url: require('../../src/assets/audio/a_rehman_sudais/24.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 25,
    title: 'Al-Furqan',
    arabicTitle: 'الفرقان',
    englishTitle: 'The Criterion',
    // url: require('../../src/assets/audio/a_rehman_sudais/25.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 26,
    title: 'Ash-Shuara',
    arabicTitle: 'الشعراء',
    englishTitle: 'The Poets',
    // url: require('../../src/assets/audio/a_rehman_sudais/26.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 27,
    title: 'An-Naml',
    arabicTitle: 'النمل',
    englishTitle: 'The Ant',
    // url: require('../../src/assets/audio/a_rehman_sudais/27.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 28,
    title: 'Al-Qasas',
    arabicTitle: 'القصص',
    englishTitle: 'The Stories',
    // url: require('../../src/assets/audio/a_rehman_sudais/28.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 29,
    title: 'Al-Ankabut',
    arabicTitle: 'العنكبوت',
    englishTitle: 'The Spider',
    // url: require('../../src/assets/audio/a_rehman_sudais/29.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 30,
    title: 'Ar-Rum',
    arabicTitle: 'الروم',
    englishTitle: 'The Romans',
    // url: require('../../src/assets/audio/a_rehman_sudais/30.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 31,
    title: 'Luqman',
    arabicTitle: 'لقمان',
    englishTitle: 'Luqman',
    // url: require('../../src/assets/audio/a_rehman_sudais/31.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 32,
    title: 'As-Sajdah',
    arabicTitle: 'السجدة',
    englishTitle: 'The Prostration',
    // url: require('../../src/assets/audio/a_rehman_sudais/32.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 33,
    title: 'Al-Ahzab',
    arabicTitle: 'الأحزاب',
    englishTitle: 'The Clans',
    // url: require('../../src/assets/audio/a_rehman_sudais/33.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 34,
    title: 'Saba',
    arabicTitle: 'سبأ',
    englishTitle: 'Sheba',
    // url: require('../../src/assets/audio/a_rehman_sudais/34.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 35,
    title: 'Fatir',
    arabicTitle: 'فاطر',
    englishTitle: 'The Originator',
    // url: require('../../src/assets/audio/a_rehman_sudais/35.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 36,
    title: 'Ya-Sin',
    arabicTitle: 'يس',
    englishTitle: 'Ya Sin',
    // url: require('../../src/assets/audio/a_rehman_sudais/36.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 37,
    title: 'As-Saffat',
    arabicTitle: 'الصافات',
    englishTitle: 'Those who set the Ranks',
    // url: require('../../src/assets/audio/a_rehman_sudais/37.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 38,
    title: 'Sad',
    arabicTitle: 'ص',
    englishTitle: 'Sad',
    // url: require('../../src/assets/audio/a_rehman_sudais/38.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 39,
    title: 'Az-Zumar',
    arabicTitle: 'الزمر',
    englishTitle: 'The Groups',
    // url: require('../../src/assets/audio/a_rehman_sudais/39.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 40,
    title: 'Ghafir',
    arabicTitle: 'غافر',
    englishTitle: 'The Forgiver',
    // url: require('../../src/assets/audio/a_rehman_sudais/40.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 41,
    title: 'Fussilat',
    arabicTitle: 'فصلت',
    englishTitle: 'Explained in Detail',
    // url: require('../../src/assets/audio/a_rehman_sudais/41.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 42,
    title: 'Ash-Shura',
    arabicTitle: 'الشورى',
    englishTitle: 'The Consultation',
    // url: require('../../src/assets/audio/a_rehman_sudais/42.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 43,
    title: 'Az-Zukhruf',
    arabicTitle: 'الزخرف',
    englishTitle: 'Ornaments of Gold',
    // url: require('../../src/assets/audio/a_rehman_sudais/43.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 44,
    title: 'Ad-Dukhan',
    arabicTitle: 'الدخان',
    englishTitle: 'The Smoke',
    // url: require('../../src/assets/audio/a_rehman_sudais/44.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 45,
    title: 'Al-Jathiyah',
    arabicTitle: 'الجاثية',
    englishTitle: 'The Crouching',
    // url: require('../../src/assets/audio/a_rehman_sudais/45.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 46,
    title: 'Al-Ahqaf',
    arabicTitle: 'الأحقاف',
    englishTitle: 'The Wind-Curved Sandhills',
    // url: require('../../src/assets/audio/a_rehman_sudais/46.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 47,
    title: 'Muhammad',
    arabicTitle: 'محمد',
    englishTitle: 'Muhammad',
    // url: require('../../src/assets/audio/a_rehman_sudais/47.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 48,
    title: 'Al-Fath',
    arabicTitle: 'الفتح',
    englishTitle: 'The Victory',
    // url: require('../../src/assets/audio/a_rehman_sudais/48.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 49,
    title: 'Al-Hujurat',
    arabicTitle: 'الحجرات',
    englishTitle: 'The Rooms',
    // url: require('../../src/assets/audio/a_rehman_sudais/49.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 50,
    title: 'Qaf',
    arabicTitle: 'ق',
    englishTitle: 'Qaf',
    // url: require('../../src/assets/audio/a_rehman_sudais/50.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 51,
    title: 'Az-Zariyat',
    arabicTitle: 'الذاريات',
    englishTitle: 'The Winnowing Winds',
    // url: require('../../src/assets/audio/a_rehman_sudais/51.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 52,
    title: 'At-Tur',
    arabicTitle: 'الطور',
    englishTitle: 'The Mount',
    // url: require('../../src/assets/audio/a_rehman_sudais/52.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 53,
    title: 'An-Najm',
    arabicTitle: 'النجم',
    englishTitle: 'The Star',
    // url: require('../../src/assets/audio/a_rehman_sudais/53.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 54,
    title: 'Al-Qamar',
    arabicTitle: 'القمر',
    englishTitle: 'The Moon',
    // url: require('../../src/assets/audio/a_rehman_sudais/54.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 55,
    title: 'Ar-Rahman',
    arabicTitle: 'الرحمن',
    englishTitle: 'The Beneficent',
    // url: require('../../src/assets/audio/a_rehman_sudais/55.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 56,
    title: 'Al-Waqiah',
    arabicTitle: 'الواقعة',
    englishTitle: 'The Event',
    // url: require('../../src/assets/audio/a_rehman_sudais/56.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 57,
    title: 'Al-Hadid',
    arabicTitle: 'الحديد',
    englishTitle: 'The Iron',
    // url: require('../../src/assets/audio/a_rehman_sudais/57.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 58,
    title: 'Al-Mujadila',
    arabicTitle: 'المجادلة',
    englishTitle: 'The Pleading Woman',
    // url: require('../../src/assets/audio/a_rehman_sudais/58.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 59,
    title: 'Al-Hashr',
    arabicTitle: 'الحشر',
    englishTitle: 'The Gathering',
    // url: require('../../src/assets/audio/a_rehman_sudais/59.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 60,
    title: 'Al-Mumtahinah',
    arabicTitle: 'الممتحنة',
    englishTitle: 'She that is to be examined',
    // url: require('../../src/assets/audio/a_rehman_sudais/60.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 61,
    title: 'As-Saff',
    arabicTitle: 'الصف',
    englishTitle: 'The Ranks',
    // url: require('../../src/assets/audio/a_rehman_sudais/61.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 62,
    title: 'Al-Jumuah',
    arabicTitle: 'الجمعة',
    englishTitle: 'Friday',
    // url: require('../../src/assets/audio/a_rehman_sudais/62.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 63,
    title: 'Al-Munafiqun',
    arabicTitle: 'المنافقون',
    englishTitle: 'The Hypocrites',
    // url: require('../../src/assets/audio/a_rehman_sudais/63.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 64,
    title: 'At-Taghabun',
    arabicTitle: 'التغابن',
    englishTitle: 'Mutual Disillusion',
    // url: require('../../src/assets/audio/a_rehman_sudais/64.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 65,
    title: 'At-Talaq',
    arabicTitle: 'الطلاق',
    englishTitle: 'Divorce',
    // url: require('../../src/assets/audio/a_rehman_sudais/65.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 66,
    title: 'At-Tahrim',
    arabicTitle: 'التحريم',
    englishTitle: 'The Prohibition',
    // url: require('../../src/assets/audio/a_rehman_sudais/66.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 67,
    title: 'Al-Mulk',
    arabicTitle: 'الملك',
    englishTitle: 'The Sovereignty',
    // url: require('../../src/assets/audio/a_rehman_sudais/67.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 68,
    title: 'Al-Qalam',
    arabicTitle: 'القلم',
    englishTitle: 'The Pen',
    // url: require('../../src/assets/audio/a_rehman_sudais/68.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 69,
    title: 'Al-Haqqah',
    arabicTitle: 'الحاقة',
    englishTitle: 'The Reality',
    // url: require('../../src/assets/audio/a_rehman_sudais/69.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 70,
    title: 'Al-Maarij',
    arabicTitle: 'المعارج',
    englishTitle: 'The Ascending Stairways',
    // url: require('../../src/assets/audio/a_rehman_sudais/70.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 71,
    title: 'Nuh',
    arabicTitle: 'نوح',
    englishTitle: 'Noah',
    // url: require('../../src/assets/audio/a_rehman_sudais/71.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 72,
    title: 'Al-Jinn',
    arabicTitle: 'الجن',
    englishTitle: 'The Jinn',
    // url: require('../../src/assets/audio/a_rehman_sudais/72.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 73,
    title: 'Al-Muzzammil',
    arabicTitle: 'المزمل',
    englishTitle: 'The Enshrouded One',
    // url: require('../../src/assets/audio/a_rehman_sudais/73.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 74,
    title: 'Al-Muddathir',
    arabicTitle: 'المدثر',
    englishTitle: 'The Cloaked One',
    // url: require('../../src/assets/audio/a_rehman_sudais/74.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 75,
    title: 'Al-Qiyamah',
    arabicTitle: 'القيامة',
    englishTitle: 'The Resurrection',
    // url: require('../../src/assets/audio/a_rehman_sudais/75.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 76,
    title: 'Al-Insan',
    arabicTitle: 'الانسان',
    englishTitle: 'Man',
    // url: require('../../src/assets/audio/a_rehman_sudais/76.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 77,
    title: 'Al-Mursalat',
    arabicTitle: 'المرسلات',
    englishTitle: 'The Emissaries',
    // url: require('../../src/assets/audio/a_rehman_sudais/77.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 78,
    title: 'An-Naba',
    arabicTitle: 'النبإ',
    englishTitle: 'The Tidings',
    // url: require('../../src/assets/audio/a_rehman_sudais/78.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 79,
    title: 'An-Naziat',
    arabicTitle: 'النازعات',
    englishTitle: 'Those who drag forth',
    // url: require('../../src/assets/audio/a_rehman_sudais/79.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 80,
    title: 'Abasa',
    arabicTitle: 'عبس',
    englishTitle: 'He frowned',
    // url: require('../../src/assets/audio/a_rehman_sudais/80.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 81,
    title: 'At-Takwir',
    arabicTitle: 'التكوير',
    englishTitle: 'The Overthrowing',
    // url: require('../../src/assets/audio/a_rehman_sudais/81.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 82,
    title: 'Al-Infitar',
    arabicTitle: 'الإنفطار',
    englishTitle: 'The Cleaving',
    // url: require('../../src/assets/audio/a_rehman_sudais/82.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 83,
    title: 'Al-Mutaffifin',
    arabicTitle: 'المطففين',
    englishTitle: 'Defrauding',
    // url: require('../../src/assets/audio/a_rehman_sudais/83.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 84,
    title: 'Al-Inshiqaq',
    arabicTitle: 'الإنشقاق',
    englishTitle: 'The Splitting Open',
    // url: require('../../src/assets/audio/a_rehman_sudais/84.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 85,
    title: 'Al-Buruj',
    arabicTitle: 'البروج',
    englishTitle: 'The Mansions of the Stars',
    // url: require('../../src/assets/audio/a_rehman_sudais/85.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 86,
    title: 'At-Tariq',
    arabicTitle: 'الطارق',
    englishTitle: 'The Morning Star',
    // url: require('../../src/assets/audio/a_rehman_sudais/86.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 87,
    title: 'Al-Ala',
    arabicTitle: 'الأعلى',
    englishTitle: 'The Most High',
    // url: require('../../src/assets/audio/a_rehman_sudais/87.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 88,
    title: 'Al-Ghashiyah',
    arabicTitle: 'الغاشية',
    englishTitle: 'The Overwhelming',
    // url: require('../../src/assets/audio/a_rehman_sudais/88.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 89,
    title: 'Al-Fajr',
    arabicTitle: 'الفجر',
    englishTitle: 'The Dawn',
    // url: require('../../src/assets/audio/a_rehman_sudais/89.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 90,
    title: 'Al-Balad',
    arabicTitle: 'البلد',
    englishTitle: 'The City',
    // url: require('../../src/assets/audio/a_rehman_sudais/90.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 91,
    title: 'Ash-Shams',
    arabicTitle: 'الشمس',
    englishTitle: 'The Sun',
    // url: require('../../src/assets/audio/a_rehman_sudais/91.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 92,
    title: 'Al-Lail',
    arabicTitle: 'الليل',
    englishTitle: 'The Night',
    // url: require('../../src/assets/audio/a_rehman_sudais/92.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 93,
    title: 'Ad-Duha',
    arabicTitle: 'الضحى',
    englishTitle: 'The Morning Hours',
    // url: require('../../src/assets/audio/a_rehman_sudais/93.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 94,
    title: 'Al-Inshirah',
    arabicTitle: 'الشرح',
    englishTitle: 'The Relief',
    // url: require('../../src/assets/audio/a_rehman_sudais/94.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 95,
    title: 'At-Tin',
    arabicTitle: 'التين',
    englishTitle: 'The Fig',
    // url: require('../../src/assets/audio/a_rehman_sudais/95.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 96,
    title: 'Al-Alaq',
    arabicTitle: 'العلق',
    englishTitle: 'The Clot',
    // url: require('../../src/assets/audio/a_rehman_sudais/96.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 97,
    title: 'Al-Qadr',
    arabicTitle: 'القدر',
    englishTitle: 'The Power',
    // url: require('../../src/assets/audio/a_rehman_sudais/97.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 98,
    title: 'Al-Bayyinah',
    arabicTitle: 'البينة',
    englishTitle: 'The Clear Proof',
    // url: require('../../src/assets/audio/a_rehman_sudais/98.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 99,
    title: 'Az-Zalzalah',
    arabicTitle: 'الزلزلة',
    englishTitle: 'The Earthquake',
    // url: require('../../src/assets/audio/a_rehman_sudais/99.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 100,
    title: 'Al-Adiyat',
    arabicTitle: 'العاديات',
    englishTitle: 'The Courser',
    // url: require('../../src/assets/audio/a_rehman_sudais/100.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 101,
    title: 'Al-Qariah',
    arabicTitle: 'القارعة',
    englishTitle: 'The Calamity',
    // url: require('../../src/assets/audio/a_rehman_sudais/101.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 102,
    title: 'At-Takathur',
    arabicTitle: 'التكاثر',
    englishTitle: 'The Rivalry in world increase',
    // url: require('../../src/assets/audio/a_rehman_sudais/102.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 103,
    title: 'Al-Asr',
    arabicTitle: 'العصر',
    englishTitle: 'The Declining Day',
    // url: require('../../src/assets/audio/a_rehman_sudais/103.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 104,
    title: 'Al-Humazah',
    arabicTitle: 'الهمزة',
    englishTitle: 'The Traducer',
    // url: require('../../src/assets/audio/a_rehman_sudais/104.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 105,
    title: 'Al-Fil',
    arabicTitle: 'الفيل',
    englishTitle: 'The Elephant',
    // url: require('../../src/assets/audio/a_rehman_sudais/105.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 106,
    title: 'Quraish',
    arabicTitle: 'قريش',
    englishTitle: 'Quraysh',
    // url: require('../../src/assets/audio/a_rehman_sudais/106.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 107,
    title: 'Al-Maun',
    arabicTitle: 'الماعون',
    englishTitle: 'The Small Kindness',
    // url: require('../../src/assets/audio/a_rehman_sudais/107.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 108,
    title: 'Al-kausar',
    arabicTitle: 'الكوثر',
    englishTitle: 'Abundance',
    // url: require('../../src/assets/audio/a_rehman_sudais/108.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 109,
    title: 'Al-Kafirun',
    arabicTitle: 'الكافرون',
    englishTitle: 'The Disbelievers',
    // url: require('../../src/assets/audio/a_rehman_sudais/109.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 110,
    title: 'An-Nasr',
    arabicTitle: 'النصر',
    englishTitle: 'The Help',
    // url: require('../../src/assets/audio/a_rehman_sudais/110.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 111,
    title: 'Al-lahab',
    arabicTitle: 'اللهب',
    englishTitle: 'The Palm Fibre',
    // url: require('../../src/assets/audio/a_rehman_sudais/111.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 112,
    title: 'Al-Ikhlas',
    arabicTitle: 'الإخلاص',
    englishTitle: 'The Sincerity',
    // url: require('../../src/assets/audio/a_rehman_sudais/112.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 113,
    title: 'Al-Falaq',
    arabicTitle: 'الفلق',
    englishTitle: 'The Daybreak',
    // url: require('../../src/assets/audio/a_rehman_sudais/113.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  },
  {
    surahNo: 114,
    title: 'An-Nas',
    arabicTitle: 'الناس',
    englishTitle: 'The Mankind',
    // url: require('../../src/assets/audio/a_rehman_sudais/114.mp3'),
    // image: require('../../src/assets/images/recitersImage/a_rehman_sudais/abdul_rahman_al_sudais.png'),
  }];
