
export const styles = (theme) => ({
  container: {
    backgroundImage: `URL(${require("../../../assets/images/designImages/bgImageDark.png")})`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    minHeight: "320px",
    display: "flex",
    color: theme.colors.TEXT,
    flexDirection: "column",
  },
  iconContainer: {
    marginRight: "5px",
    justifyContent: "center",
    alignSelf: "center",
  },
  heading: {
    color: theme.colors.HEADER_ITEMS,
    fontWeight: "bold",
    fontFamily: "Raleway",
    textAlign: "center",
  },
  navbar: {
    width: "95%",
    height: "fit-content",
    display: "flex",
    justifyContent: "space-between",
    marginTop: 20,
    alignSelf: "center",
  },
  navIcons: {
    color: theme.colors.HEADER_ITEMS,
    fontSize: "30",
  },
  // searchStyles
  searchbarContainer: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#ffffff26",
    width: "100%",
    maxWidth: "300px",
    alignSelf: "center",
    borderRadius: "21px",
    flexDirection: "row",
    flexWrap: "wrap",
    padding: "0 3px",
  },
  searchStyle: {
    color: theme.colors.HEADER_ITEMS,
    alignSelf: "center",
    justifyContent: "center",
    backgroundColor: theme.colors.TRANSPARENT,
    flex: "1",
    border: "none",
    outline: "none",
    borderWidth: 0,
    borderRadius: "21px",
    fontSize: "15px",
    padding: 15,
  },
  searchIcon: {
    marginRight: "10px",
    fontSize: 13,
    color: theme.colors.HEADER_ITEMS,
  },
  toggle: {
    fontSize: 40,
    marginLeft: "4px",
  },
});